set(CHIP F401xC)
set(PROVIDER st)
set(BOARD_BSP meteostation)
set(HAVE_BOOT TRUE)
set(BOOT_ADDRESS 0x8000000)

set(BOOT_LIBS "")

list(APPEND BOOT_LIBS BSP::CORE)
list(APPEND BOOT_LIBS BSP::USB)
list(APPEND BOOT_LIBS BSP::NoOs)
    
