set(CHIP F103xB)
set(PROVIDER st)
set(HAVE_BOOT TRUE)
set(BOOT_ADDRESS 0x8000000)

set(BOOT_LIBS "")

list(APPEND BOOT_LIBS BSP::CORE)
list(APPEND BOOT_LIBS BSP::USB)
list(APPEND BOOT_LIBS BSP::NoOs)
    
